[build-system]
requires = [
    "scikit-build-core>=0.8.0",
    "pybind11>=2.10.0",
]
build-backend = "scikit_build_core.build"

[project]
name = "gymnasium-procgen"
version = "0.11.0"
description = "Procedurally Generated Game-Like RL Environments"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Farama Foundation", email = "jkterry@farama.org"}
]
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.19.0",
    "gym>=0.18.0",
    "gym3>=0.3.3",
]

[project.optional-dependencies]
test = [
    "pytest>=6.0.0",
    "pytest-benchmark"
]

[project.urls]
Homepage = "https://github.com/Farama-Foundation/gymnasium-procgen"
Documentation = "https://gymnasium-procgen.farama.org"
Repository = "https://github.com/Farama-Foundation/gymnasium-procgen"
"Bug Tracker" = "https://github.com/Farama-Foundation/gymnasium-procgen/issues"

[tool.scikit-build]
cmake.build-type = "Release"
build.verbose = true

# Include Python source files
# wheel.packages = ["gymnasium_procgen"]

metadata.version.provider = "scikit_build_core.metadata.regex"
metadata.version.input = "version.txt"
metadata.version.regex = "^(?P<value>.+)$"

[tool.cibuildwheel]
# Skip 32-bit wheels, PyPy & musllinux
skip = ["*-win32", "*i686", "*-musllinux*"]

build-frontend = "build"
manylinux-x86_64-image = "manylinux-x86_64-vcpkg:latest"
manylinux-aarch64-image = "manylinux-aarch64-vcpkg:latest"

[tool.cibuildwheel.linux]
environment-pass = ["GITHUB_REF"]

[tool.cibuildwheel.macos]
before-all = [
    "brew update",
    "brew upgrade",
    "brew install automake autoconf libtool"
]

# macOS arm64
[[tool.cibuildwheel.overrides]]
select = "*-macosx_arm64"
environment = { PIP_ONLY_BINARY = "numpy", VCPKG_DEFAULT_TRIPLET = "arm64-osx-native", VCPKG_FEATURE_FLAGS = "-compilertracking", MACOSX_DEPLOYMENT_TARGET = "13.0" }

# Windows x64
[[tool.cibuildwheel.overrides]]
select = "*-win_amd64"
environment = { PIP_ONLY_BINARY = "numpy", VCPKG_DEFAULT_TRIPLET = "x64-windows", VCPKG_FEATURE_FLAGS = "-compilertracking" }

# Linux x86-64 (manylinux)
[[tool.cibuildwheel.overrides]]
select = "*-manylinux_x86_64"
environment = { PIP_ONLY_BINARY = "numpy", VCPKG_FEATURE_FLAGS = "-compilertracking" }

# Linux ARM64 (manylinux)
[[tool.cibuildwheel.overrides]]
select = "*-manylinux_aarch64"
environment = { PIP_ONLY_BINARY = "numpy", VCPKG_FEATURE_FLAGS = "-compilertracking" }
